Feautre/implement token info endpoints
Taraxa-project/tara-erc20-info-api pull request #3
Opened 2023-01-11 14:49 UTC by VargaElod23

2023-01-11 16:17 UTC, rattrap requested changes

2023-01-11 16:17 UTC, rattrap commented on src/staking/delegation.service.ts
> +    )}/validators?show_fully_delegated=true&show_my_validators=false`;
Why only fully delegated validators?

2023-01-11 16:17 UTC, rattrap commented on src/staking/delegation.service.ts
> +    }
This whole thing can be moved to a separate method to keep things DRY

2023-01-11 16:17 UTC, rattrap commented on src/token/token.service.ts
> +      (await this.totalSupply()) -
These are all strings

2023-01-11 16:17 UTC, rattrap commented on src/token/token.service.ts
> +      ((await this.totalStaked()) /
Again. These methods return strings

2023-01-11 19:47 UTC, VargaElod23 commented on src/staking/delegation.service.ts
> +    )}/validators?show_fully_delegated=true&show_my_validators=false`;
Isn't that flag meaning: `include fully delegated validators too` ?

2023-01-13 12:41 UTC, Malak67 requested changes
Small changes needed

2023-01-13 12:41 UTC, Malak67 commented on src/staking/delegation.service.ts
> +    delegationData.forEach((node: any) => {
We don't know the type for Node? If not then we should add node?.totalDelegation (or create a type or interfance for it).

2023-01-13 12:41 UTC, Malak67 commented on src/staking/delegation.service.ts
> +      if (node.totalDelegation && node.currentCommission) {
Same here

2023-01-13 12:41 UTC, Malak67 commented on src/staking/delegation.service.ts
> +      const realTimeDelegationData = await firstValueFrom(
Same comment as in the other PR.

2023-01-13 12:41 UTC, Malak67 commented on src/staking/delegation.service.ts
> +      throw new InternalServerErrorException(
Remove this (see node PR)

2023-01-13 12:41 UTC, Malak67 commented on src/token/token.service.ts
> +      const realTimePriceData = await firstValueFrom(
Same here

2023-01-13 12:41 UTC, Malak67 commented on src/token/token.service.ts
> +      throw new InternalServerErrorException(
Remove this

2023-01-13 13:53 UTC, merged